---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  vars:
  environment: "{{environment_vars}}"  
  
  tasks:
    - name: Ping host - {{ inventory_hostname }}
      ping:
      register: result

    - name: Response
      debug:
        msg: "{{ result.ping }}"

    - name: Setting fact `data_set_name` for use by this sample
      set_fact:
        data_set_name: "{{ ansible_user | upper }}.SOME.DATA.SET"


                                                                 
    - name: Create a PDS data set {{ data_set_name }}
      zos_data_set:
        name: "{{ data_set_name }}"
        type: pds
        size: 5M
        format: fb
        record_length: 25
        replace: yes
      register: result

    - name: Response create a PDS data set {{ data_set_name }}                                                              
      debug:
        msg: "{{ result }}" 
           
