---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: '{{environment_vars}}'
    

  tasks:
    - name: Sort the data set based on age in descending order
      zos_mvs_raw:
        program_name: sort
        dds:
          - dd_output:
              dd_name: sysout
              return_content:
                type: text
          - dd_data_set:
              dd_name: sortin
              data_set_name: USER.SORT.INPUT
              disposition: shr
          - dd_data_set:
              dd_name: sortout
              data_set_name: USER.SORT.INPUT
              disposition: old             
          - dd_input: 
              dd_name: sysin  
              content: "SORT FIELDS=(9,2,BI,D)"
